name: gitworkflow

on:
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  integration-test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.5
        env:
          MYSQL_ROOT_PASSWORD: "password"
          MYSQL_DATABASE: "csye_assign5"
        ports:
          - 3306:3306  # Corrected the port
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Use Node.js 18
        uses: actions/setup-node@v2 
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests without DB
        run: npm test
