name: Build ami on aws

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  test_and_build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Github code checkout
        uses: actions/checkout@v3
          
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build application artifact
        run: zip -r webapp.zip ./ -x '*.git*'
      
      - name: Packer Init
        run: packer init packer-debian.pkr.hcl || exit 1
        working-directory: packer
      
      - name: Validate Packer Template
        run: packer validate packer-debian.pkr.hcl || (echo "Packer template validation failed!" && exit 1)
        working-directory: packer
          
      - name: Build AMI
        if: success()
          run: packer build packer-debian.pkr.hcl || (echo "Packer Build failed!" && exit 1)
          working-directory: packer
          arguments: '-color=false -on-error=abort -var-file=dev.auto.pkrvars.hcl'
        env:
          PACKER_LOG: 1
        
      
